### PR TITLE
Add footer

### PR DESCRIPTION
**Pull request by Houdinic**

### CODE REVIEW

**Comment by eshellman** [comment]
not sure what this means - you should be making PRs from gutenberg1 (dev) into master. or have I confused what is production?

**Comment by Houdinic** [comment]
Did we make gutenberg1 a dev branch? I thought gutenberg1 is the production branch. Last time when deploying "last page", we made it to master first for testing and then merged changes into gutenberg1.

**Comment by eshellman** [comment]
you're correct, gutenberg1 is running production. but the correct thing to do is to first merge a commit adding the footer into master. We should not be committing directly to the gutenberg1 branch, as that is now what production is running, but at a different commit than what you're trying to merge into. However I think this PR will get us to where we should be.

**Review by eshellman — APPROVED** [review]
I think this is right

**Pull request merged**
