### PR TITLE
Updating Pipfile because it does not support version ranges on the Python interpreter version

### PR DESCRIPTION
**Pull request by ddaws**
Per the title, when I try to install dependencies I get 

```bash
$ pipenv install
Error: Python version range specifier '>=3.8' is not supported. Please use an absolute version number or specify the path to the Python executable on Pipfile.
```

Maybe this worked in an earlier version of Pipenv. I am running 

```bash
$ pipenv --version
pipenv, version 2024.0.2
```

Here is [the relevant doc](https://pipenv.pypa.io/en/latest/specifiers.html#specifying-versions-of-python). Afaik it doesn't include examples of a version range.

I also moved the `requires` and `pipenv` blocks to the top of the file because the list of deps will grow and change. It's nice to keep these smaller blocks at the top imo.

### CODE REVIEW

**Comment by eshellman** [comment]
we're on 3.9

**Comment by ddaws** [comment]
Updated to version 3.9. After a `pipenv install` this also updated the lock file

**Comment by eshellman** [comment]
I made the pipfile change on the dev branch, but I don't want to change the lock file without reviewing the change notes for any updated dependencies.

**Comment by ddaws** [comment]
Should we close this MR now that the change has been merged into the dev branch? Does the dev branch eventually get merged into the master branch?

**Comment by eshellman** [comment]
... and dev is now merged into main, and pulled from main onto appdev (which serves dev.gutenberg.org)
when we're happy with that, we'll pull onto 'prod' which is what serves www.gutenberg.org

**Pull request closed without merging**
