### PR TITLE
Gutenberg2

### PR DESCRIPTION
**Pull request by Houdinic**
edit bibrec page HTML layout so it can adjust to different screen size

### CODE REVIEW

**Comment by eshellman** [comment]
I'm assuming that somehow you have css that does media queries to show or hide the "mobile" or "standard" blocks.

1. this almost doubles the size of the payload and the amount of server-side computation. We should do load testing before putting this in production. I will try tonight.
2. it might be more maintainable to separate the mobile vs standard content block into 2 separate include files. Perhaps more performant.
3.  Screen-size and "screen' Media queries are used to trigger mobile view. If so, how will ebook readers with embedded browsers be handled? How has this code been tested?
4. at 1000px wide, there is a lot of empty space above the fold. The social buttons turn into a list which looks sill and takes up space. The QR code should drop to the very bottom.

**Comment by eshellman** [comment]
throughput drops from 35 to 27 requests/second

**Comment by Houdinic** [comment]
> I'm assuming that somehow you have css that does media queries to show or hide the "mobile" or "standard" blocks.
> 
> 1. this almost doubles the size of the payload and the amount of server-side computation. We should do load testing before putting this in production. I will try tonight.
> 2. it might be more maintainable to separate the mobile vs standard content block into 2 separate include files. Perhaps more performant.
> 3. Screen-size and "screen' Media queries are used to trigger mobile view. If so, how will ebook readers with embedded browsers be handled? How has this code been tested?
> 4. at 1000px wide, there is a lot of empty space above the fold. The social buttons turn into a list which looks sill and takes up space. The QR code should drop to the very bottom.

This update is done based on someone outside PG to improve browsing experience on mobile device and it makes mobile, especially cell phone display better. 
The social button turns to be a list because one of the div is deleted and I can fix it. 
Blank space will take a lot of space on Desktop display but on mobile device it looks normal.

**Comment by Houdinic** [comment]
This update will not affect kindle built-in browser. It has the same display like desktop which is a problem needs to be fixed in the future.

**Comment by eshellman** [comment]
This is using same css as current?

**Comment by eshellman** [comment]
I guess I don't understand why the content needs to be duplicated - the css should be able to do it with unduplicated content

**Comment by Houdinic** [comment]
I need to delete some of the HTML for mobile display and keep them for standard display. I can try use smaller block to achieve the same effect.

I updated the css file in gutenbergsite repo in style.css yesterday.

**Comment by Houdinic** [comment]
Karen and I are working to rewrite the HTML to avoid duplicate code and achieve this goal. I revert it back to the yesterday version as a temporary solution for this. And there is an extra column in the table removed by last commit.

**Comment by eshellman** [comment]
IIRC the extra column is used by the javascript that makes a page for printing.

**Comment by Houdinic** [comment]
We didn't use JavaScript on new site as I remembered. Do we still keep that function? On the page, it seems not to be able to print. I can revert that commit if needed.

**Comment by eshellman** [comment]
seems to still work on dev

**Comment by eshellman** [comment]
Any updates?

**Comment by Houdinic** [comment]
> Any updates?

I think we can close this PR and I will wait until they set up new dev site to test css on it. If the css cannot fix this problem, I will start to rewrite HTML again.

**Comment by eshellman** [comment]
ok. I'll reset the gutenberg2 branch.

**Comment by eshellman** [comment]
maybe it's best not to use gutenberg2 branch for feature or bugfix development

**Pull request closed without merging**
